name: Release

on:
  release:
    types: [published]

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          scope: '@octocat'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run Biome
        run: yarn lint
      - name: Run TypeScript
        run: yarn typecheck
      - name: Build dist
        run: yarn build
      - name: Publish to npm
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
